version: '3.2'
services:
  web:
    build: ./web
    command: npm run watch
    networks:
      - asb-network
    depends_on:
      - client
  client:
    build: ./client
  webserver:
    image: nginx:alpine
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
    volumes:
      - type: bind
        source: ./client/build
        target: /var/www/html
      - ./nginx/app.conf:/etc/nginx/conf.d/default.conf
    networks:
      - asb-network

networks:
  asb-network:
