version: '3.2'
services:
  web:
    build: ./web
    command: npm run watch
    ports:
      - "8080:8080"
    volumes:
      - ./web:/usr/src/app
  client:
    ports:
      - "3000:3000"
    build: ./client
    command: npm run start
    volumes:
      - ./client:/usr/src/app
  webserver:
    image: nginx:alpine
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
